// backend/src/data/jobsDataset.js
// ─────────────────────────────────────────────────────────────────────────────
// Static job listings mapped to role IDs.
// This is the ONLY file that changes when you plug in JSearch / RapidAPI later.
// The jobService.js interface stays identical — this just becomes an API call.
// ─────────────────────────────────────────────────────────────────────────────

export const jobListings = {
  'frontend-dev': [
    {
      id: 'fe_001',
      title: 'Frontend Developer Intern',
      company: 'Swiggy',
      logo: '🍊',
      location: 'Bangalore, India',
      type: 'Internship',
      mode: 'Hybrid',
      experience: '0–1 years',
      salary: '₹20,000–35,000/month',
      skills: ['React', 'JavaScript', 'CSS', 'REST APIs'],
      applyLink: 'https://careers.swiggy.com',
      posted: '3 days ago',
      description: 'Build and maintain React components for Swiggy\'s consumer-facing web apps. Work alongside senior engineers on high-traffic UI features.',
    },
    {
      id: 'fe_002',
      title: 'Junior Frontend Engineer',
      company: 'Razorpay',
      logo: '💳',
      location: 'Bangalore, India',
      type: 'Full-time',
      mode: 'Hybrid',
      experience: '0–2 years',
      salary: '₹6–10 LPA',
      skills: ['React', 'TypeScript', 'Redux', 'Sass'],
      applyLink: 'https://razorpay.com/jobs',
      posted: '1 week ago',
      description: 'Join the Dashboard team to build Razorpay\'s merchant-facing web products. Strong React fundamentals required.',
    },
    {
      id: 'fe_003',
      title: 'React Developer',
      company: 'Infosys',
      logo: '🔷',
      location: 'Pune / Bangalore, India',
      type: 'Full-time',
      mode: 'On-site',
      experience: '0–1 years',
      salary: '₹3.6–5 LPA',
      skills: ['React', 'JavaScript', 'HTML', 'CSS', 'Git'],
      applyLink: 'https://careers.infosys.com',
      posted: '5 days ago',
      description: 'Freshers welcome. Build scalable frontend applications for global clients. Training program provided.',
    },
    {
      id: 'fe_004',
      title: 'UI Engineer',
      company: 'CRED',
      logo: '💜',
      location: 'Bangalore, India',
      type: 'Full-time',
      mode: 'Hybrid',
      experience: '1–3 years',
      salary: '₹10–18 LPA',
      skills: ['React', 'TypeScript', 'GraphQL', 'Performance'],
      applyLink: 'https://careers.cred.club',
      posted: '2 weeks ago',
      description: 'Own UI quality for CRED\'s premium fintech experience. Obsess over performance, accessibility, and design fidelity.',
    },
  ],

  'backend-dev': [
    {
      id: 'be_001',
      title: 'Backend Developer Intern',
      company: 'Zepto',
      logo: '🛒',
      location: 'Mumbai, India',
      type: 'Internship',
      mode: 'Hybrid',
      experience: '0 years',
      salary: '₹25,000–40,000/month',
      skills: ['Node.js', 'Express', 'MongoDB', 'REST APIs'],
      applyLink: 'https://www.zeptonow.com/careers',
      posted: '4 days ago',
      description: 'Build microservices powering Zepto\'s 10-minute delivery engine. Work on real production systems from day one.',
    },
    {
      id: 'be_002',
      title: 'Junior Backend Engineer',
      company: 'PhonePe',
      logo: '💙',
      location: 'Bangalore, India',
      type: 'Full-time',
      mode: 'Hybrid',
      experience: '0–2 years',
      salary: '₹8–14 LPA',
      skills: ['Node.js', 'Java', 'MySQL', 'Redis', 'Docker'],
      applyLink: 'https://www.phonepe.com/careers',
      posted: '1 week ago',
      description: 'Design and build APIs handling millions of transactions. Own your service end-to-end from architecture to deployment.',
    },
    {
      id: 'be_003',
      title: 'Node.js Developer',
      company: 'Wipro',
      logo: '🟡',
      location: 'Hyderabad / Bangalore, India',
      type: 'Full-time',
      mode: 'On-site',
      experience: '0–1 years',
      salary: '₹3.5–5.5 LPA',
      skills: ['Node.js', 'Express', 'MySQL', 'REST APIs', 'Git'],
      applyLink: 'https://careers.wipro.com',
      posted: '6 days ago',
      description: 'Freshers with strong Node.js fundamentals. Work on enterprise-grade backend systems for global clients.',
    },
    {
      id: 'be_004',
      title: 'API Developer',
      company: 'Meesho',
      logo: '🛍️',
      location: 'Bangalore, India',
      type: 'Full-time',
      mode: 'Hybrid',
      experience: '1–2 years',
      salary: '₹9–15 LPA',
      skills: ['Node.js', 'PostgreSQL', 'Redis', 'Kafka', 'Docker'],
      applyLink: 'https://meesho.io/jobs',
      posted: '3 days ago',
      description: 'Build the seller and logistics APIs powering Meesho\'s marketplace for 150M+ customers.',
    },
  ],

  'fullstack-dev': [
    {
      id: 'fs_001',
      title: 'Full Stack Developer Intern',
      company: 'Groww',
      logo: '📈',
      location: 'Bangalore, India',
      type: 'Internship',
      mode: 'Hybrid',
      experience: '0 years',
      salary: '₹25,000–45,000/month',
      skills: ['React', 'Node.js', 'MongoDB', 'REST APIs'],
      applyLink: 'https://groww.in/careers',
      posted: '2 days ago',
      description: 'Build features on Groww\'s investing platform used by 10M+ users. Full ownership from design to deployment.',
    },
    {
      id: 'fs_002',
      title: 'SDE-1 (Full Stack)',
      company: 'Flipkart',
      logo: '🛒',
      location: 'Bangalore, India',
      type: 'Full-time',
      mode: 'Hybrid',
      experience: '0–2 years',
      salary: '₹18–28 LPA',
      skills: ['React', 'Java', 'MySQL', 'Microservices', 'Docker'],
      applyLink: 'https://www.flipkartcareers.com',
      posted: '1 week ago',
      description: 'Shape Flipkart\'s shopping experience for 400M+ customers. Great for engineers who enjoy owning full features.',
    },
    {
      id: 'fs_003',
      title: 'MERN Stack Developer',
      company: 'Zoho',
      logo: '🔵',
      location: 'Chennai / Remote, India',
      type: 'Full-time',
      mode: 'Remote-friendly',
      experience: '0–1 years',
      salary: '₹5–9 LPA',
      skills: ['MongoDB', 'Express', 'React', 'Node.js', 'JavaScript'],
      applyLink: 'https://careers.zoho.com',
      posted: '5 days ago',
      description: 'Build SaaS products used by 100M+ users globally. Zoho has a strong track record of growing freshers into senior engineers.',
    },
    {
      id: 'fs_004',
      title: 'Full Stack Engineer',
      company: 'BrowserStack',
      logo: '🌐',
      location: 'Mumbai / Remote, India',
      type: 'Full-time',
      mode: 'Remote',
      experience: '1–3 years',
      salary: '₹12–20 LPA',
      skills: ['React', 'Node.js', 'PostgreSQL', 'TypeScript', 'AWS'],
      applyLink: 'https://www.browserstack.com/careers',
      posted: '4 days ago',
      description: 'Build the platform 50,000+ companies use for testing. Remote-first culture with great engineering bar.',
    },
  ],

  'data-analyst': [
    {
      id: 'da_001',
      title: 'Data Analyst Intern',
      company: 'Zomato',
      logo: '🍕',
      location: 'Gurgaon, India',
      type: 'Internship',
      mode: 'Hybrid',
      experience: '0 years',
      salary: '₹20,000–35,000/month',
      skills: ['SQL', 'Python', 'Excel', 'Data Visualization'],
      applyLink: 'https://www.zomato.com/careers',
      posted: '1 week ago',
      description: 'Analyze restaurant and delivery data to uncover growth opportunities. Build dashboards for business teams.',
    },
    {
      id: 'da_002',
      title: 'Business Analyst',
      company: 'Accenture',
      logo: '🔷',
      location: 'Bangalore, India',
      type: 'Full-time',
      mode: 'Hybrid',
      experience: '0–1 years',
      salary: '₹4.5–7 LPA',
      skills: ['SQL', 'Excel', 'Power BI', 'Python', 'Statistics'],
      applyLink: 'https://www.accenture.com/in-en/careers',
      posted: '3 days ago',
      description: 'Translate data into business decisions. Work across industries including retail, BFSI, and healthcare.',
    },
    {
      id: 'da_003',
      title: 'Data Analyst',
      company: 'Nykaa',
      logo: '💄',
      location: 'Mumbai, India',
      type: 'Full-time',
      mode: 'Hybrid',
      experience: '0–2 years',
      salary: '₹6–10 LPA',
      skills: ['SQL', 'Python', 'Tableau', 'Google Analytics'],
      applyLink: 'https://careers.nykaa.com',
      posted: '6 days ago',
      description: 'Drive data-informed decisions for one of India\'s fastest-growing e-commerce brands. Strong SQL is a must.',
    },
  ],

  'ml-engineer': [
    {
      id: 'ml_001',
      title: 'ML Engineer Intern',
      company: 'Google India',
      logo: '🌈',
      location: 'Bangalore, India',
      type: 'Internship',
      mode: 'Hybrid',
      experience: '0 years',
      salary: '₹1.2–1.8 LPA/month',
      skills: ['Python', 'TensorFlow', 'Machine Learning', 'Statistics'],
      applyLink: 'https://careers.google.com',
      posted: '2 weeks ago',
      description: 'Work on real ML problems at Google scale. Requires strong ML fundamentals and Python skills.',
    },
    {
      id: 'ml_002',
      title: 'Junior Data Scientist',
      company: 'Mu Sigma',
      logo: '📐',
      location: 'Bangalore, India',
      type: 'Full-time',
      mode: 'On-site',
      experience: '0–1 years',
      salary: '₹6–10 LPA',
      skills: ['Python', 'ML', 'Statistics', 'SQL', 'Pandas'],
      applyLink: 'https://www.mu-sigma.com/careers',
      posted: '4 days ago',
      description: 'Solve business problems using ML and analytics. Great entry point for ML career with strong mentorship.',
    },
    {
      id: 'ml_003',
      title: 'AI/ML Developer',
      company: 'Ola',
      logo: '🚗',
      location: 'Bangalore, India',
      type: 'Full-time',
      mode: 'Hybrid',
      experience: '1–3 years',
      salary: '₹12–22 LPA',
      skills: ['Python', 'PyTorch', 'MLOps', 'Computer Vision', 'Docker'],
      applyLink: 'https://www.olacabs.com/careers',
      posted: '1 week ago',
      description: 'Build ML models for ride prediction, pricing, and ETA. Work on India-scale real-time ML systems.',
    },
  ],

  'devops-engineer': [
    {
      id: 'do_001',
      title: 'DevOps Intern',
      company: 'HashedIn by Deloitte',
      logo: '🔷',
      location: 'Bangalore, India',
      type: 'Internship',
      mode: 'Hybrid',
      experience: '0 years',
      salary: '₹20,000–30,000/month',
      skills: ['Linux', 'Docker', 'AWS', 'CI/CD', 'Git'],
      applyLink: 'https://hashedin.com/careers',
      posted: '1 week ago',
      description: 'Learn DevOps in a fast-paced product engineering environment. Strong Linux and scripting fundamentals needed.',
    },
    {
      id: 'do_002',
      title: 'Site Reliability Engineer',
      company: 'Freshworks',
      logo: '🌿',
      location: 'Chennai, India',
      type: 'Full-time',
      mode: 'Hybrid',
      experience: '0–2 years',
      salary: '₹8–15 LPA',
      skills: ['Docker', 'Kubernetes', 'AWS', 'Python', 'Monitoring'],
      applyLink: 'https://www.freshworks.com/company/careers',
      posted: '5 days ago',
      description: 'Keep Freshworks\' SaaS products reliable for 68,000+ global customers. On-call rotation with great compensation.',
    },
  ],

  'mobile-dev': [
    {
      id: 'mob_001',
      title: 'React Native Developer Intern',
      company: 'ShareChat',
      logo: '📸',
      location: 'Bangalore, India',
      type: 'Internship',
      mode: 'Hybrid',
      experience: '0 years',
      salary: '₹20,000–40,000/month',
      skills: ['React Native', 'JavaScript', 'REST APIs', 'Firebase'],
      applyLink: 'https://sharechat.com/careers',
      posted: '3 days ago',
      description: 'Build features for India\'s leading regional social media app with 400M+ users. Strong JS skills needed.',
    },
    {
      id: 'mob_002',
      title: 'Mobile Developer',
      company: 'Paytm',
      logo: '💰',
      location: 'Noida / Bangalore, India',
      type: 'Full-time',
      mode: 'Hybrid',
      experience: '0–2 years',
      salary: '₹6–12 LPA',
      skills: ['React Native', 'Flutter', 'Firebase', 'REST APIs'],
      applyLink: 'https://jobs.paytm.com',
      posted: '1 week ago',
      description: 'Build mobile features for India\'s largest fintech super-app. Cross-platform experience preferred.',
    },
  ],

  'software-engineer': [
    {
      id: 'swe_001',
      title: 'Software Engineer (SDE-1)',
      company: 'Amazon India',
      logo: '📦',
      location: 'Bangalore / Hyderabad, India',
      type: 'Full-time',
      mode: 'Hybrid',
      experience: '0–1 years',
      salary: '₹20–32 LPA',
      skills: ['Data Structures', 'Algorithms', 'Java', 'System Design'],
      applyLink: 'https://www.amazon.jobs',
      posted: '1 week ago',
      description: 'Build systems at Amazon scale. Bar-raising interview focused on DSA and system design.',
    },
    {
      id: 'swe_002',
      title: 'Graduate Software Engineer',
      company: 'Microsoft India',
      logo: '🪟',
      location: 'Hyderabad, India',
      type: 'Full-time',
      mode: 'Hybrid',
      experience: '0 years',
      salary: '₹22–35 LPA',
      skills: ['Algorithms', 'Problem Solving', 'C++', 'Python', 'System Design'],
      applyLink: 'https://careers.microsoft.com',
      posted: '2 weeks ago',
      description: 'Start your career at Microsoft. Build products used by billions. Strong DSA focus in interviews.',
    },
    {
      id: 'swe_003',
      title: 'Software Engineer',
      company: 'TCS NQT',
      logo: '🔵',
      location: 'Pan India',
      type: 'Full-time',
      mode: 'On-site',
      experience: '0 years',
      salary: '₹3.6–7 LPA',
      skills: ['Programming Fundamentals', 'Problem Solving', 'SQL', 'Git'],
      applyLink: 'https://www.tcs.com/careers',
      posted: '5 days ago',
      description: 'Join India\'s largest IT firm through NQT. Clear path for freshers with structured growth and training.',
    },
    {
      id: 'swe_004',
      title: 'Engineer I',
      company: 'Atlassian',
      logo: '🔷',
      location: 'Bangalore, India',
      type: 'Full-time',
      mode: 'Remote',
      experience: '0–2 years',
      salary: '₹18–28 LPA',
      skills: ['Algorithms', 'Java', 'Python', 'Distributed Systems'],
      applyLink: 'https://www.atlassian.com/company/careers',
      posted: '1 week ago',
      description: 'Fully remote. Build Jira, Confluence, and Trello for 10M+ teams. Excellent engineering culture.',
    },
  ],

  'cloud-engineer': [
    {
      id: 'cl_001',
      title: 'Cloud Engineer Intern',
      company: 'Capgemini',
      logo: '☁️',
      location: 'Pune, India',
      type: 'Internship',
      mode: 'Hybrid',
      experience: '0 years',
      salary: '₹18,000–28,000/month',
      skills: ['AWS', 'Linux', 'Docker', 'Python', 'Networking'],
      applyLink: 'https://www.capgemini.com/careers',
      posted: '1 week ago',
      description: 'Get hands-on with cloud infrastructure for enterprise clients. AWS certification training included.',
    },
    {
      id: 'cl_002',
      title: 'Junior Cloud Developer',
      company: 'Thoughtworks',
      logo: '💡',
      location: 'Bangalore, India',
      type: 'Full-time',
      mode: 'Hybrid',
      experience: '0–2 years',
      salary: '₹8–14 LPA',
      skills: ['AWS', 'Docker', 'Terraform', 'CI/CD', 'Linux'],
      applyLink: 'https://www.thoughtworks.com/careers',
      posted: '3 days ago',
      description: 'Work on cloud-native solutions for global clients. Agile mindset and infrastructure-as-code focus.',
    },
  ],

  'api-developer': [
    {
      id: 'api_001',
      title: 'API Developer',
      company: 'Postman',
      logo: '📮',
      location: 'Bangalore, India',
      type: 'Full-time',
      mode: 'Hybrid',
      experience: '0–2 years',
      salary: '₹8–16 LPA',
      skills: ['REST APIs', 'Node.js', 'GraphQL', 'API Design', 'Testing'],
      applyLink: 'https://www.postman.com/company/careers',
      posted: '1 week ago',
      description: 'Build the tools that developers worldwide use to design and test APIs. Meta-role: APIs about APIs.',
    },
    {
      id: 'api_002',
      title: 'Integration Developer Intern',
      company: 'MuleSoft (Salesforce)',
      logo: '🔗',
      location: 'Bangalore, India',
      type: 'Internship',
      mode: 'Hybrid',
      experience: '0 years',
      salary: '₹30,000–45,000/month',
      skills: ['REST APIs', 'Node.js', 'OAuth', 'Webhooks', 'Documentation'],
      applyLink: 'https://www.salesforce.com/company/careers',
      posted: '5 days ago',
      description: 'Build integration connectors used by enterprise clients worldwide. Strong API fundamentals required.',
    },
  ],
};

// Fallback jobs shown when role has no specific listings
export const genericJobs = [
  {
    id: 'gen_001',
    title: 'Software Developer',
    company: 'Infosys',
    logo: '🔷',
    location: 'Pan India',
    type: 'Full-time',
    mode: 'On-site',
    experience: '0–1 years',
    salary: '₹3.6–6 LPA',
    skills: ['Programming', 'Problem Solving', 'Git'],
    applyLink: 'https://careers.infosys.com',
    posted: '1 week ago',
    description: 'General software development role for freshers. Strong fundamentals and training program included.',
  },
];
