// backend/src/data/rolesDataset.js
// ─────────────────────────────────────────────────────────────────────────────
// Static role definitions used by the TF-IDF matching engine.
// Skills are ordered by importance (first = higher conceptual weight).
// To add/edit roles: just update this file — the engine picks it up automatically.
// ─────────────────────────────────────────────────────────────────────────────

export const roles = [
  {
    id: 'frontend-dev',
    role: 'Frontend Developer',
    emoji: '🎨',
    category: 'Web Development',
    skills: [
      'react', 'javascript', 'html', 'css', 'typescript',
      'redux', 'tailwind', 'sass', 'webpack', 'vite',
      'responsive design', 'rest api', 'git', 'figma', 'jest',
      'nextjs', 'graphql', 'accessibility', 'performance',
    ],
    coreSkills: ['react', 'javascript', 'html', 'css'], // must-haves for the role
    description: 'Build beautiful, performant user interfaces for the web.',
    avgSalary: '₹4–14 LPA',
    demand: 'High',
    growthPath: ['Senior Frontend', 'UI Tech Lead', 'Full Stack Developer'],
  },
  {
    id: 'backend-dev',
    role: 'Backend Developer',
    emoji: '⚙️',
    category: 'Web Development',
    skills: [
      'nodejs', 'express', 'python', 'java', 'rest api',
      'mysql', 'postgresql', 'mongodb', 'redis', 'jwt',
      'authentication', 'docker', 'aws', 'prisma', 'graphql',
      'microservices', 'kafka', 'nginx', 'linux', 'git',
    ],
    coreSkills: ['nodejs', 'express', 'rest api', 'database'],
    description: 'Design and build server-side logic, APIs, and databases.',
    avgSalary: '₹5–16 LPA',
    demand: 'High',
    growthPath: ['Senior Backend', 'Backend Architect', 'Engineering Manager'],
  },
  {
    id: 'fullstack-dev',
    role: 'Full Stack Developer',
    emoji: '🔥',
    category: 'Web Development',
    skills: [
      'react', 'nodejs', 'javascript', 'express', 'html', 'css',
      'mongodb', 'mysql', 'postgresql', 'rest api', 'jwt',
      'git', 'docker', 'typescript', 'redux', 'prisma',
      'deployment', 'aws', 'vite', 'authentication',
    ],
    coreSkills: ['react', 'nodejs', 'javascript', 'rest api'],
    description: 'Own both frontend and backend — build entire products end-to-end.',
    avgSalary: '₹6–18 LPA',
    demand: 'Very High',
    growthPath: ['Senior Full Stack', 'Tech Lead', 'CTO / Startup Founder'],
  },
  {
    id: 'data-analyst',
    role: 'Data Analyst',
    emoji: '📊',
    category: 'Data & Analytics',
    skills: [
      'python', 'sql', 'excel', 'tableau', 'power bi',
      'pandas', 'numpy', 'data visualization', 'statistics',
      'mysql', 'postgresql', 'google analytics', 'looker',
      'jupyter', 'matplotlib', 'seaborn', 'etl', 'reporting',
    ],
    coreSkills: ['sql', 'python', 'data visualization', 'statistics'],
    description: 'Transform raw data into actionable business insights.',
    avgSalary: '₹4–12 LPA',
    demand: 'High',
    growthPath: ['Senior Analyst', 'Data Scientist', 'Analytics Manager'],
  },
  {
    id: 'ml-engineer',
    role: 'Machine Learning Engineer',
    emoji: '🤖',
    category: 'AI / ML',
    skills: [
      'python', 'machine learning', 'deep learning', 'tensorflow', 'pytorch',
      'scikit-learn', 'numpy', 'pandas', 'nlp', 'computer vision',
      'statistics', 'sql', 'docker', 'mlops', 'jupyter',
      'feature engineering', 'model deployment', 'aws', 'data pipelines',
    ],
    coreSkills: ['python', 'machine learning', 'statistics', 'numpy'],
    description: 'Build and deploy intelligent ML systems and models.',
    avgSalary: '₹8–25 LPA',
    demand: 'Very High',
    growthPath: ['Senior ML Engineer', 'AI Researcher', 'ML Architect'],
  },
  {
    id: 'devops-engineer',
    role: 'DevOps Engineer',
    emoji: '🚀',
    category: 'Infrastructure',
    skills: [
      'docker', 'kubernetes', 'aws', 'linux', 'ci/cd',
      'jenkins', 'github actions', 'terraform', 'ansible',
      'bash', 'python', 'monitoring', 'nginx', 'git',
      'microservices', 'cloud', 'security', 'networking',
    ],
    coreSkills: ['docker', 'linux', 'ci/cd', 'cloud'],
    description: 'Automate deployment pipelines and manage cloud infrastructure.',
    avgSalary: '₹6–20 LPA',
    demand: 'High',
    growthPath: ['Senior DevOps', 'Cloud Architect', 'SRE'],
  },
  {
    id: 'mobile-dev',
    role: 'Mobile App Developer',
    emoji: '📱',
    category: 'Mobile',
    skills: [
      'react native', 'flutter', 'javascript', 'dart',
      'android', 'ios', 'firebase', 'rest api', 'redux',
      'typescript', 'expo', 'mobile ui', 'app store', 'git',
    ],
    coreSkills: ['react native', 'javascript', 'rest api'],
    description: 'Build cross-platform or native mobile applications.',
    avgSalary: '₹5–15 LPA',
    demand: 'High',
    growthPath: ['Senior Mobile Dev', 'Mobile Lead', 'Full Stack'],
  },
  {
    id: 'software-engineer',
    role: 'Software Engineer (General)',
    emoji: '💻',
    category: 'Engineering',
    skills: [
      'data structures', 'algorithms', 'problem solving', 'javascript',
      'python', 'java', 'git', 'rest api', 'sql', 'system design',
      'oop', 'debugging', 'testing', 'linux', 'agile',
    ],
    coreSkills: ['data structures', 'algorithms', 'problem solving'],
    description: 'Build software systems across domains — versatile and in demand.',
    avgSalary: '₹5–20 LPA',
    demand: 'Very High',
    growthPath: ['Senior SWE', 'Staff Engineer', 'Engineering Manager'],
  },
  {
    id: 'cloud-engineer',
    role: 'Cloud Engineer',
    emoji: '☁️',
    category: 'Infrastructure',
    skills: [
      'aws', 'azure', 'gcp', 'docker', 'kubernetes', 'terraform',
      'linux', 'networking', 'security', 'ci/cd', 'python',
      'bash', 'iam', 'serverless', 'microservices', 'monitoring',
    ],
    coreSkills: ['aws', 'docker', 'linux', 'networking'],
    description: 'Design and manage scalable cloud infrastructure.',
    avgSalary: '₹7–22 LPA',
    demand: 'High',
    growthPath: ['Senior Cloud Engineer', 'Solutions Architect', 'Cloud Architect'],
  },
  {
    id: 'api-developer',
    role: 'API / Integration Developer',
    emoji: '🔌',
    category: 'Web Development',
    skills: [
      'rest api', 'graphql', 'nodejs', 'python', 'express',
      'jwt', 'oauth', 'postman', 'swagger', 'microservices',
      'mysql', 'mongodb', 'redis', 'kafka', 'webhooks',
      'api design', 'documentation', 'testing', 'git',
    ],
    coreSkills: ['rest api', 'nodejs', 'authentication', 'database'],
    description: 'Design, build, and integrate APIs that power modern applications.',
    avgSalary: '₹5–14 LPA',
    demand: 'High',
    growthPath: ['Senior API Developer', 'Backend Architect', 'Platform Engineer'],
  },
];
